### ISSUE TITLE
Error - "local variable 'xp_prices' referenced before assignment"

### ISSUE THREAD

**Issue by janush1985** [woblers/rightmove_webscraper.py#12] opened 2018-07-17 09:11 UTC
Hello,

Below piece of code produces following error:

     93         Create data lists from xpaths:
     94         price_pcm = tree.xpath(xp_prices)
     95         titles = tree.xpath(xp_titles)
     96         addresses = tree.xpath(xp_addresses)

**UnboundLocalError: local variable 'xp_prices' referenced before assignment** 

`import pandas as pd
import rightmove_webscraper
import numpy as np

url = "https://www.rightmove.co.uk/new-homes-for-sale/find.html?searchType=SALE&locationIdentifier=REGION%5E87490&insId=1&radius=0.0&minPrice=&maxPrice=&minBedrooms=&maxBedrooms=&displayPropertyType=&maxDaysSinceAdded=&_includeSSTC=on&sortByPriceDescending=&primaryDisplayPropertyType=&secondaryDisplayPropertyType=&oldDisplayPropertyType=&oldPrimaryDisplayPropertyType=&newHome=true&auction=false"

rightmove_data = rightmove_webscraper.rightmove_data(url)`

Any clues on what has wrong with this?

Best,
Janush

**Comment by woblers** [comment] 2018-07-17 13:36
It looks like rightmove have added a new search functionality for 'New Homes For Sale' which creates a different type of URL which starts with "https://www.rightmove.co.uk/new-homes-for-sale ..."

The scraper looks for the tag "/property-for-sale/" in the URL to define the `xp_prices` variable - since it is not found the variable is not defined. I can fix this easily I just need to test that all the other x-paths still work in the 'New Homes For Sale' searches

**Comment by janush1985** [comment] 2018-07-18 14:23
That "http://www.rightmove.co.uk/new-homes-for-sale/" start of the URL has been there all along as I had been using the package with these types of URLS to look for new homes on sale, up to a point when it started crashing around the 12th of this month.

You sure this is the cause?

**Comment by woblers** [comment] 2018-07-25 17:12
Yes I'm pretty sure this is the cause. You might not have changed what you're doing, but rightmove have changed the formulation of the URLs for new home searches, and this wasn't accounted for in the old version. Please use the updated version I just committed - I've tested with your URL and it worked. I'll update the version on Pypi shortly.

**Closed by woblers** 2018-07-25 17:12 UTC
